version: '2'
services:
  mongodb:
    image: "mongo"
    ports:
     - "27017:27017"
  backend:
    build: ./todolist-backend/
    ports:
      - "5000:5000"
    volumes:
      - ./todolist-backend:/usr/src/app
    depends_on:
      - mongodb
  frontend:
    build: ./todolist-frontend/
    ports:
      - "3000:3000"
    volumes:
      - ./todolist-frontend:/usr/src/app
    depends_on:
      - backend